//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("Cake.Prompt")]
[assembly: AssemblyDescription("Cake Prompt AddIn")]
[assembly: AssemblyProduct("Cake.Prompt")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0")]
[assembly: AssemblyCopyright("Copyright © Yves Schmid 2017")]
[assembly: CLSCompliant(true)]

